# Generated by Django 2.2 on 2019-04-03 06:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageBaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=10, help_text='Max value up to 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('counter', models.PositiveIntegerField(default=0, editable=False)),
                ('slug', models.SlugField(null=True, unique='True')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoBaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=10, help_text='Max value up to 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('counter', models.PositiveIntegerField(default=0, editable=False)),
                ('video', models.FileField(upload_to='media/video/%Y/%m/%d/')),
                ('subtitles', models.FileField(blank=True, null=True, upload_to='media/video/%Y/%m/%d/')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='basetype.PageBaseType')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextBaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=10, help_text='Max value up to 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('counter', models.PositiveIntegerField(default=0, editable=False)),
                ('text', models.TextField(max_length=4800)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text', to='basetype.PageBaseType')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioBaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=10, help_text='Max value up to 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('counter', models.PositiveIntegerField(default=0, editable=False)),
                ('bitrate', models.PositiveIntegerField(help_text='kbit/s')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio', to='basetype.PageBaseType')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
    ]
