# Generated by Django 2.1.7 on 2019-03-31 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='String (up to %(max_length)s)', max_length=100)),
                ('order', models.DecimalField(decimal_places=2, default=0, help_text='Number (up to 999)', max_digits=5)),
                ('counter', models.PositiveIntegerField(default=0, editable=False)),
                ('bitrate', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageBaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='String (up to %(max_length)s)', max_length=100)),
                ('order', models.DecimalField(decimal_places=2, default=0, help_text='Number (up to 999)', max_digits=5)),
                ('counter', models.PositiveIntegerField(default=0, editable=False)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basetype_pagebasetype_related+', to='basetype.AudioBaseType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextBaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='String (up to %(max_length)s)', max_length=100)),
                ('order', models.DecimalField(decimal_places=2, default=0, help_text='Number (up to 999)', max_digits=5)),
                ('counter', models.PositiveIntegerField(default=0, editable=False)),
                ('text', models.TextField(max_length=4800)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoBaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='String (up to %(max_length)s)', max_length=100)),
                ('order', models.DecimalField(decimal_places=2, default=0, help_text='Number (up to 999)', max_digits=5)),
                ('counter', models.PositiveIntegerField(default=0, editable=False)),
                ('video', models.FileField(upload_to='media/video/%Y/%m/%d/')),
                ('subtitles', models.FileField(blank=True, null=True, upload_to='media/video/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pagebasetype',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basetype_pagebasetype_related+', to='basetype.TextBaseType'),
        ),
        migrations.AddField(
            model_name='pagebasetype',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basetype_pagebasetype_related+', to='basetype.VideoBaseType'),
        ),
    ]
