# Generated by Django 2.1.7 on 2019-03-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basetype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobasetype',
            name='order',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Number up to 999', max_digits=3),
        ),
        migrations.AlterField(
            model_name='audiobasetype',
            name='title',
            field=models.CharField(help_text='String up to 100 max_length', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagebasetype',
            name='order',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Number up to 999', max_digits=3),
        ),
        migrations.AlterField(
            model_name='pagebasetype',
            name='title',
            field=models.CharField(help_text='String up to 100 max_length', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbasetype',
            name='order',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Number up to 999', max_digits=3),
        ),
        migrations.AlterField(
            model_name='textbasetype',
            name='title',
            field=models.CharField(help_text='String up to 100 max_length', max_length=100),
        ),
        migrations.AlterField(
            model_name='videobasetype',
            name='order',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Number up to 999', max_digits=3),
        ),
        migrations.AlterField(
            model_name='videobasetype',
            name='title',
            field=models.CharField(help_text='String up to 100 max_length', max_length=100),
        ),
    ]
