# Generated by Django 2.1.7 on 2019-03-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basetype', '0002_auto_20190331_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobasetype',
            name='order',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Number up to 999', max_digits=3),
        ),
        migrations.AlterField(
            model_name='pagebasetype',
            name='order',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Number up to 999', max_digits=3),
        ),
        migrations.AlterField(
            model_name='textbasetype',
            name='order',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Number up to 999', max_digits=3),
        ),
        migrations.AlterField(
            model_name='videobasetype',
            name='order',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Number up to 999', max_digits=3),
        ),
    ]
