# Generated by Django 2.1.7 on 2019-03-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basetype', '0003_auto_20190331_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobasetype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audiobasetype',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pagebasetype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagebasetype',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='textbasetype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textbasetype',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videobasetype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videobasetype',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
