# Generated by Django 2.1.7 on 2019-04-01 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basetype', '0005_auto_20190401_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagebasetype',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='pagebasetype',
            name='text',
        ),
        migrations.RemoveField(
            model_name='pagebasetype',
            name='video',
        ),
        migrations.AddField(
            model_name='audiobasetype',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basetype_audiobasetype_related', to='basetype.PageBaseType'),
        ),
        migrations.AddField(
            model_name='textbasetype',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basetype_textbasetype_related', to='basetype.PageBaseType'),
        ),
        migrations.AddField(
            model_name='videobasetype',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basetype_videobasetype_related', to='basetype.PageBaseType'),
        ),
    ]
