# Generated by Django 2.1.7 on 2019-04-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basetype', '0006_auto_20190401_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebasetype',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
