# Generated by Django 2.1.7 on 2019-04-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basetype', '0009_auto_20190401_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbasetype',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text', to='basetype.PageBaseType'),
        ),
        migrations.AlterField(
            model_name='videobasetype',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='basetype.PageBaseType'),
        ),
    ]
